# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa76e44af445114c66260aa551eaf4ef3bdb8d82240c907d9b57cdd363560602b5a2a023e073b800e706056bd0a162eb4bf05704e71e5e36398652dfd27ae80c

test:
  secret_key_base: 15af35b7ef05bd08669153907457ae222abb86ded2e11e1eb7c3ba6e68108ca7669d375e6a9f28caae27f39614443b36786bb6a051ab573c2bbf06eb9de69413

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
